#62: Secure access through LAN
ruuvi/ruuvi.gwui.html pull request #63
Opened 2021-05-04 07:52 UTC by TheSomeMan

@ojousima could you please check the translation into Finnish in auth.html and index.html?

2021-05-04 09:09 UTC, ojousima commented on src/auth.html
> +                        $('input#pwd').attr('placeholder', "Salasana");
Ok

2021-05-04 09:22 UTC, ojousima requested changes
Looks good, thanks. 

Some translations might need fine-tuning later, but I wrote what makes most sense to me right now. If I missed some translation with "ok" or change, let me know.

2021-05-04 09:22 UTC, ojousima commented on src/auth.html
> +                <span lang="fi">Ruuvi-verkkoliittymän sisäänkirjautuminen</span>
Is this for the gateway configuration interface login? If yes,

"Gateway Web Interface Login" in English,
"Gatewayn selainliittymän sisäänkirjautuminen" in Finnish

2021-05-04 09:22 UTC, ojousima commented on src/auth.html
> +                <span lang="fi">Valtuutus onnistui.</span>
"Sisäänkirjautuminen onnistui"

2021-05-04 09:22 UTC, ojousima commented on src/auth.html
> +            <span lang="fi">Valitse kieli</span>
Ok

2021-05-04 09:22 UTC, ojousima commented on src/auth.html
> +                            <span lang="fi">Käyttäjänimi:</span>
Ok

2021-05-04 09:22 UTC, ojousima commented on src/auth.html
> +                            <span lang="fi">Salasana:</span>
Ok

2021-05-04 09:22 UTC, ojousima commented on src/auth.html
> +                            <span lang="fi">Väärä käyttäjätunnus tai salasana</span>
Ok

2021-05-04 09:22 UTC, ojousima commented on src/auth.html
> +                <span lang="fi">KIRJAUDU SISÄÄN</span>
Ok

2021-05-04 09:22 UTC, ojousima commented on src/index.html
> +                    <span lang="fi">Todennus (käytettäessä lähiverkosta)</span>
Kirjautuminen (käytettäessä lähiverkosta)

2021-05-04 09:22 UTC, ojousima commented on src/index.html
> +                    <p lang="fi">Voit rajoittaa pääsyä yhdyskäytävälle paikallisverkosta (WiFi tai Ethernet).</p>
"Voit rajoittaa pääsyä Gatewaylle paikallisverkosta (WiFi tai Ethernet)."

2021-05-04 09:22 UTC, ojousima commented on src/index.html
> +                        <span lang="fi">Ruuvi-todennus (perustuu MD5 + SHA256: een)</span>
Ruuvi-kirjautuminen (perustuu MD5 + SHA256:een)

2021-05-04 09:22 UTC, ojousima commented on src/index.html
> +                        <span lang="fi">Digest-todennus</span>
Salattu kirjautuminen

2021-05-04 09:22 UTC, ojousima commented on src/index.html
> +                        <span lang="fi">Perustodennus</span>
Salaamaton kirjautuminen

2021-05-04 09:22 UTC, ojousima commented on src/index.html
> +                        <span lang="fi">Salli käyttö ilman salasanasuojausta</span>
ok

2021-05-04 09:22 UTC, ojousima commented on src/index.html
> +                        <span lang="fi">Takaisin</span>
ok

2021-05-04 09:22 UTC, ojousima commented on src/index.html
> +                        <span lang="fi">Jatka</span>
ok

2021-05-07 09:43 UTC, TheSomeMan commented
hi @ojousima , is translation ok now?

2021-05-07 10:00 UTC, ojousima approved these changes
Thanks, translation is ok

2021-05-14 07:38 UTC, TheSomeMan commented
@ojousima could you please check translation from my recent commit:

```
<span lang="en">Deny access from the local network</span>
<span lang="fi">Estä pääsy paikallisverkosta</span>

<span lang="en">Access denied.</span>
<span lang="fi">Pääsy evätty.</span>

```

2021-05-14 09:23 UTC, ojousima commented
Translation is ok

2021-05-14 09:48 UTC, ojousima approved these changes

2021-05-18 10:19 UTC, merged